### ISSUE TITLE
[Suggestion] Biome Bundle Compat

### ISSUE THREAD

**Issue by SlimefrogSocial** [supermassimo/DynamicTrees-ExC#35] opened 2020-08-19 14:20 UTC
Pretty self explanitory, just wanted compatibility for Biome Bundle (and a lot of other mods you have already planned or finished, great work!)

**Comment by supermassimo** [comment] 2020-08-19 14:49
Duplicate of https://github.com/supermassimo/DynamicTrees-ExC/issues/21

**Closed as completed by supermassimo** 2020-08-19 14:49 UTC
Labels: duplicate
