### ISSUE TITLE
Crash with 1.16.5 latest version

### ISSUE THREAD

**Issue by RodrigoTaipe93** [supermassimo/DynamicTrees-ExC#67] opened 2021-05-12 13:57 UTC
Hello, there!

I wanted to try the latest version of Dynamic Trees. I included this add-on, but my game crashed.

To reproduce you basically add this mod (latest version published on Curse), and check the mod menu. When trying to click in the Dynamic Trees Quarks add on, you will get this crash:

- https://paste.ee/p/uz7vX

Info about the mods:

- Dynamic Trees version: DynamicTrees-1.16.5-0.10.0-Beta10

- Dynamic Trees Plus version: DynamicTreesPlus-1.16.5-0.1.0-Beta8

- Quarks version: Quark-r2.4-311

- Forge Version: 36.1.16

**Comment by DcNdrew** [comment] 2021-05-27 13:19
And another Quark crash.

https://paste.ee/p/c27mF

**Comment by supermassimo** [comment] 2021-05-27 18:02
This seems to be caused by the world module being disabled in Quark. Will be fixed soon but that can be a workaround

**Comment by SP00K-E** [comment] 2021-05-27 23:42
Quark, per changelogs, changed the way its biome configuration works in the latest update. This might be the source of the error.

**Comment by meepstertron** [comment] 2021-05-30 07:44
hello i have the same problem i wanted to use it in my modpack maybe there is a work arround
![Screenshot 2021-05-30 094223](https://user-images.githubusercontent.com/62438310/120096404-973c5480-c12b-11eb-8b2b-92af2da94def.jpg)

**Comment by Harleyoc1** [comment] 2021-05-30 08:09
Please use Quark `r2.4-311` for the time being.

**Comment by supermassimo** [comment] 2021-05-31 18:23
Fixed in [DT-Quark 2.0.4](https://www.curseforge.com/minecraft/mc-mods/dynamic-trees-quark/files/3331311)

**Closed as completed by supermassimo** 2021-05-31 18:23 UTC
Labels: bug, need more info, module: Quark, 1.16.5
