### ISSUE TITLE
[Suggestion] Compatibility for Redwoods

### ISSUE THREAD

**Issue by dracoattila** [supermassimo/DynamicTrees-ExC#39] opened 2020-08-30 13:06 UTC
https://www.curseforge.com/minecraft/mc-mods/redwoods
It would be awesome if this mod could get a dynamic tree addon. It's a port of the old Extrabiomes XL mod most memorible woods.

**Comment by supermassimo** [comment] 2020-09-05 15:46
Duplicate of https://github.com/supermassimo/DynamicTrees-ExC/issues/1

**Closed as completed by supermassimo** 2020-09-05 15:46 UTC
Labels: duplicate, 1.12.2
