### ISSUE TITLE
The Quark update has been released. Raises an error on startup.

### ISSUE THREAD

**Issue by GnomTocha** [supermassimo/DynamicTrees-ExC#69] opened 2021-05-27 17:35 UTC
At startup, the phrase "Dynamic Trees for Quark (dtquark) encountered an error during the common_setup event
phase" is highlighted.
![image](https://user-images.githubusercontent.com/75666317/119871424-1b73b980-bf2b-11eb-8888-2dc49e64090e.png)

**Comment by supermassimo** [comment] 2021-05-27 18:01
Duplicate of https://github.com/supermassimo/DynamicTrees-ExC/issues/67

**Closed as completed by supermassimo** 2021-05-27 18:01 UTC
Labels: duplicate
