### ISSUE TITLE
Crashing server and client

### ISSUE THREAD

**Issue by MrTrilB** [supermassimo/DynamicTrees-ExC#3] opened 2020-04-13 15:03 UTC
[crash-2020-04-13_09.59.04-server.txt](https://github.com/supermassimo/DynamicTrees-ExC/files/4470026/crash-2020-04-13_09.59.04-server.txt)
Hi I have been having major errors with your mod unfortunately. it has crashed both client and server on startup.

**Comment by supermassimo** [comment] 2020-04-14 14:58
duplicate of https://github.com/supermassimo/DynamicTrees-ExC/issues/2

**Closed as completed** 2020-04-14 14:58 UTC
Labels: bug, duplicate
