### ISSUE TITLE
Nether "thinks" are being spawned around the classic world

### ISSUE THREAD

**Issue by pjindras** [supermassimo/DynamicTrees-ExC#52] opened 2020-10-27 20:25 UTC
Hello, after update dynamic trees, this happens me, i have never seen this, only after update.

![Snímek obrazovky (27)](https://user-images.githubusercontent.com/45400186/97357996-e458ff00-189a-11eb-8bd4-557273eea485.png)

**Comment by Harleyoc1** [comment] 2020-10-27 22:40
Version numbers? Logs? Mod list?

**Comment by pjindras** [comment] 2020-10-27 22:44
lastest version of dynamic trees and of dynamic trees natura, mods:
dont worry about mod versions thats older mod list, the dynamic trees i have lastest version.
   Mods:
 
       | State | ID                 | Version            | Source                                        | Signature                                |
       |:----- |:------------------ |:------------------ |:--------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft          | 1.12.2             | minecraft.jar                                 | None                                     |
       | LCH   | mcp                | 9.42               | minecraft.jar                                 | None                                     |
       | LCH   | FML                | 8.0.99.99          | forge.jar                                     | None                                     |
       | LCH   | forge              | 14.23.5.2847       | forge.jar                                     | None                                     |
       | LCH   | spongeapi          | 7.1.0-5ef8b0e3     | spongeforge-1.12.2-2838-7.1.10.jar            | None                                     |
       | LCH   | sponge             | 1.12.2-7.1.10      | spongeforge-1.12.2-2838-7.1.10.jar            | None                                     |
       | LCH   | spongeforge        | 1.12.2-2838-7.1.10 | spongeforge-1.12.2-2838-7.1.10.jar            | None                                     |
       | LCH   | srm-hooks          | 1.12.2-1.0.0       | minecraft.jar                                 | None                                     |
       | LCH   | itemblacklist      | 1.4.3              | ItemBlacklist-1.4.3.jar                       | None                                     |
       | LCH   | bspkrscore         | 7.6.0.1            | [1.12]bspkrsCore-universal-7.6.0.1.jar        | None                                     |
       | LCH   | treecapitator      | 1.43.0             | [1.12]TreeCapitator-client-1.43.0.jar         | None                                     |
       | LCH   | aiimprovements     | 0.0.1.3            | AIImprovements-1.12-0.0.1b3.jar               | None                                     |
       | LCH   | backpack           | 3.0.2              | backpack-3.0.2-1.12.2.jar                     | None                                     |
       | LCH   | battletowers       | 1.6.5              | BattleTowers-1.12.2.jar                       | None                                     |
       | LCH   | biomesoplenty      | 7.0.1.2441         | BiomesOPlenty-1.12.2-7.0.1.2441-universal.jar | None                                     |
       | LCH   | bookshelf          | 2.3.590            | Bookshelf-1.12.2-2.3.590.jar                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | chesttransporter   | 2.8.8              | ChestTransporter-1.12.2-2.8.8.jar             | None                                     |
       | LCH   | chococraft         | 0.9.8.0            | chococraft_1.12.2-0.9.8.0.jar                 | None                                     |
       | LCH   | llibrary           | 1.7.19             | llibrary-1.7.19-1.12.2.jar                    | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | cqrepoured         | 1.12.1A            | ChocolateQuestRepoured-1.12.2-1.12.1A.jar     | None                                     |
       | LCH   | chunkpregenerator  | 2.1                | Chunk+Pregenerator+V1.12-2.2.jar              | None                                     |
       | LCH   | clumps             | 3.1.2              | Clumps-3.1.2.jar                              | None                                     |
       | LCH   | mantle             | 1.12-1.3.3.55      | Mantle-1.12-1.3.3.55.jar                      | None                                     |
       | LCH   | twilightforest     | 3.10.1013          | twilightforest-1.12.2-3.10.1013-universal.jar | None                                     |
       | LCH   | tconstruct         | 1.12.2-2.13.0.183  | TConstruct-1.12.2-2.13.0.183.jar              | None                                     |
       | LCH   | conarm             | 1.2.5.4            | conarm-1.12.2-1.2.5.4.jar                     | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCH   | customspawner      | 3.11.4             | CustomMobSpawner-3.11.5.jar                   | None                                     |
       | LCH   | mocreatures        | 12.0.5             | DrZharks MoCreatures Mod-12.0.5.jar           | None                                     |
       | LCH   | dynamictrees       | 1.12.2-0.9.7       | DynamicTrees-1.12.2-0.9.7.jar                 | None                                     |
       | LCH   | dynamictreesbop    | 1.12.2-1.4.1e      | DynamicTreesBOP-1.12.2-1.4.1e.jar             | None                                     |
       | LCH   | eplus              | 5.0.176            | EnchantingPlus-1.12.2-5.0.176.jar             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | fastfurnace        | 1.3.1              | FastFurnace-1.12.2-1.3.1.jar                  | None                                     |
       | LCH   | fastbench          | 1.7.3              | FastWorkbench-1.12.2-1.7.3.jar                | None                                     |
       | LCH   | gravestone         | 1.10.3             | gravestone-1.10.3.jar                         | None                                     |
       | LCH   | placebo            | 1.6.0              | Placebo-1.12.2-1.6.0.jar                      | None                                     |
       | LCH   | hexxitgear         | 2.8.0              | Hexxit+Gear-1.12.2-2.8.0.jar                  | None                                     |
       | LCH   | infernalmobs       | 1.7.6              | InfernalMobs-1.12.2.jar                       | None                                     |
       | LCH   | instantunify       | 1.1.2              | instantunify-1.12.2-1.1.2.jar                 | None                                     |
       | LCH   | ironchest          | 1.12.2-7.0.67.844  | ironchest-1.12.2-7.0.72.847.jar               | None                                     |
       | LCH   | mekanism           | 1.12.2-9.8.3.390   | Mekanism-1.12.2-9.8.3.390.jar                 | None                                     |
       | LCH   | mekanismgenerators | 1.12.2-9.8.3.390   | MekanismGenerators-1.12.2-9.8.3.390.jar       | None                                     |
       | LCH   | mekanismtools      | 1.12.2-9.8.3.390   | MekanismTools-1.12.2-9.8.3.390.jar            | None                                     |
       | LCH   | mekores            | 2.0.13             | mekores-2.0.13.jar                            | None                                     |
       | LCH   | natura             | 1.12.2-4.3.2.69    | natura-1.12.2-4.3.2.69.jar                    | None                                     |
       | LCH   | recipehandler      | 0.13               | NoMoreRecipeConflict-0.13(1.12.2).jar         | None                                     |
       | LCH   | ruins              | 17.2               | Ruins-1.12.2.jar                              | None                                     |
       | LCH   | secretroomsmod     | 5.6.4              | secretroomsmod-1.12.2-5.6.4.jar               | None                                     |
       | LCH   | simplecore         | 1.7.3.4            | simplecore-1.12.2-1.7.3.4.jar                 | None                                     |
       | LCH   | simpleoregen       | 4.3.4              | SimpleOreGeneration-4.3.4+mc+1.12.2.jar       | None                                     |
       | LCH   | simpleores         | 1.11.2.0           | simpleores-1.12.2-1.11.2.0.jar                | None                                     |
       | LCH   | simpletcon         | 3.0                | SimpleTcon-3.0a.jar                           | None                                     |
       | LCH   | vanillafix         | 1.0.10-SNAPSHOT    | VanillaFix-1.0.10-99.jar                      | None                                     |
       | LCH   | xlfoodmod          | 1.12.2-1.9.2       | XL-Food-Mod-1.12.2-1.9.2.jar                  | None                                     |
 
 
       Plugins:
 
       | State | ID          | Version     | Source                                  | Signature |
       |:----- |:----------- |:----------- |:--------------------------------------- |:--------- |
       | LCH   | catclearlag | 0.9.0       | CatClearLag-0.9.3.jar                   | None      |
       | LCH   | nucleus     | 1.12.1-S7.1 | Nucleus-1.12.1-S7.1-MC1.12.2-plugin.jar | None      |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
 
                                      SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
                                        com.wynprice.secretroomsmod.core.SecretRoomsTransformer
                                      SpongeCoremod (spongeforge-1.12.2-2838-7.1.10.jar)
                                        org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
  Pulsar/natura loaded Pulses: - NaturaCommons (Enabled/Forced)
                               - NaturaOverworld (Enabled/Not Forced)
                               - NaturaNether (Enabled/Not Forced)
                               - NaturaDecorative (Enabled/Not Forced)
                               - NaturaTools (Enabled/Not Forced)
                               - NaturaEntities (Enabled/Not Forced)
                               - NaturaOredict (Enabled/Forced)
                               - NaturaWorld (Enabled/Not Forced)
  Suspected Mods: Chocolate Quest Repoured Mod (cqrepoured)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
  Type: Dedicated Server (map_server.txt)

**Comment by Harleyoc1** [comment] 2020-10-27 22:49
Could very well be some sort of incompatibility with Sponge. Could you try generating worlds without Sponge and see if they still spawn?

**Comment by pjindras** [comment] 2020-10-27 22:50
ok, in version before it wasnt, but i can try it, server is with sponge, singleplayer without so lets try singleplayer

**Comment by Harleyoc1** [comment] 2020-10-27 22:53
This is most likely not dynamic trees or the addons as it doesn’t mess around with this sort of generation. Could you also check if the biome on the blocks where they spawn are the nether biome?

**Comment by pjindras** [comment] 2020-10-27 22:57
ok, in singleplayer i dont see it, on server in world  its  nether biome phantasmagoric inferno

**Comment by Harleyoc1** [comment] 2020-10-27 23:01
That is a biome from Biomes o’ Plenty. Could be an issue with Biomes o’ Plenty and Sponge perhaps?

**Comment by pjindras** [comment] 2020-10-27 23:02
yea maybe biomes plenty dynamic trees addon, it was updated too. Thanks

**Comment by Harleyoc1** [comment] 2020-10-27 23:04
Again Dynamic Trees and its addons don’t handle this sort of generation, if anything it’s a problem with base Biomes O’ Plenty and Sponge, or even another mod interfering with world gen. I would recommend removing dynamic trees and addons to see if it still occurs with sponge and the set of mods you have anyway.

**Comment by Harleyoc1** [comment] 2020-10-27 23:08
Going to close this for now as it doesn’t belong here but I don’t mind discussing it further, please take down the issue from DT  BOP too as it’s most likely not being caused by it as said above.

**Closed as completed by Harleyoc1** 2020-10-27 23:08 UTC
Labels: bug, invalid, 1.12.2
