### ISSUE TITLE
[DT Betweenlands] The Betweenlands' Ground Dried Swamp Reed acts like Bone Meal. Let it affect DT Betweenlands' trees.

### ISSUE THREAD

**Issue by MagmaSlime123** [supermassimo/DynamicTrees-ExC#77] opened 2021-09-08 20:21 UTC
In The Betweenlands, there is no bone meal. You instead use Ground Dried Swamp Reed. DT Betweenlands trees aren't effected by it.

**Comment by Harleyoc1** [comment] 2021-09-08 20:34
Duplicate of #72.

**Closed as completed by Harleyoc1** 2021-09-08 20:34 UTC
